modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="survivalbases"
version="${file.jarVersion}"
displayName="SurvivalBases"
credits="All credits reserved to ArmaCraft organization" #optional
authors="threader"
description='''
Base system mod
'''